#!/bin/bash
CDIR=`pwd`
cd ..
KDIR=`pwd`
PDIR=`pwd`/qt-logger/
export PATH="/opt/mxe/usr/bin/:$PATH"
/opt/mxe/usr/bin/i686-w64-mingw32.shared-qmake-qt5
#/opt/mxe/usr/i686-w64-mingw32.shared/qt5/bin/qmake
make -j4
make install

cp -f ${KDIR}/bin/qt-logger.exe ${PDIR}

function installDeps {
	/opt/mxe/tools/copydlldeps.sh --infile $1PDIR/qt-logger.exe \
                --destdir $PDIR/   \
                --recursivesrcdir /opt/mxe/usr/i686-w64-mingw32.shared/ \
                --srcdir $PDIR \
                --copy \
                --enforcedir /opt/mxe/usr/i686-w64-mingw32.shared/qt5/plugins/platforms/ \
                --objdump /opt/mxe/usr/bin/i686-w64-mingw32.shared-objdump
}


#
# Copy plugins
#
cp -dpR /opt/mxe/usr/i686-w64-mingw32.shared/qt5/plugins/audio ${PDIR}/
cp -dpR /opt/mxe/usr/i686-w64-mingw32.shared/qt5/plugins/renderplugins ${PDIR}/
cp -dpR /opt/mxe/usr/i686-w64-mingw32.shared/qt5/plugins/imageformats ${PDIR}/
cp -dpR /opt/mxe/usr/i686-w64-mingw32.shared/qt5/plugins/iconengines ${PDIR}/
cp -dpR /opt/mxe/usr/i686-w64-mingw32.shared/qt5/plugins/sqldrivers ${PDIR}/
cp -dpR /opt/mxe/usr/i686-w64-mingw32.shared/qt5/plugins/printsupport ${PDIR}/
cp -dpR /opt/mxe/usr/i686-w64-mingw32.shared/qt5/plugins/texttospeech ${PDIR}/

#cp -f $CDIR/qsqlcipher.dll ${PDIR}/sqldrivers/

cp -dpR /opt/mxe/usr/i686-w64-mingw32.shared/bin/libpcre-1.dll ${PDIR}/
cp -dpR /opt/mxe/usr/i686-w64-mingw32.shared/bin/libpcre16-0.dll ${PDIR}/
cp -dpR /opt/mxe/usr/i686-w64-mingw32.shared/bin/libpcrecpp-0.dll ${PDIR}/
cp -dpR /opt/mxe/usr/i686-w64-mingw32.shared/bin/libpcreposix-0.dll ${PDIR}/


#
# Install deps
#
installDeps $PDIR/qt-logger.exe
#installDeps $PDIR/printsupport/windowsprintersupport.dll
#installDeps $PDIR/libsqlcipher-0.dll

#cp -f $CDIR/libsqlcipher-0.dll ${PDIR}/libsqlite3-0.dll
#windeployqt 
#sudo make install
#windeployqt 
